Player controls
SlightlyDarkerBlackOne/Walk-In-A-Park pull request #4
Opened 2021-10-02 15:29 UTC by Sarvihaara

Dodano prebacivanje kontrole s psa na vlasnika i obrnuto (zasad skidanje i vracanje uzice tipkom "L", kasnije promijeniti kad definiramo pod kojim je uvjetima igracu dostupna ova opcija). Uzica se moze vratiti samo kad je pas dovoljno blizu vlasnika. Kad je skinuta, kontrola se prebacuje na psa, kad je stavljena, vraca se na vlasnika. Problem kako vratiti kraj uzice na joint od player_stone (vlasnika) jer ako se pomakne zadnji bone koja se inace spaja na taj joint na tu poziciju, ostali bone joints od uzice nece slijediti tu kost pa se uzica produljuje svaki put kad se opet stavi, zato zasad kao privremeno rjesenje teleportiram vlasnika na zadnju poziciju kraja uzice kad god se uzica vrati.

2021-10-04 14:09 UTC, SlightlyDarkerBlackOne commented on Assets/Scripts/Controls/Leash.cs
> +    public HingeJoint2D joint;
Here we use private

2021-10-04 14:48 UTC, SlightlyDarkerBlackOne commented on Assets/Scripts/Controls/Leash.cs
> +    public GameObject playerDog;
We don't need this since we are using the Singleton pattern in the PlayerController2D script. If we need to access playerDog we just do it by PlayerController2D.Instance.MethodToUse().
`#region Singleton
    public static PlayerController2D Instance { get; private set; }

    void Awake() {
        if (Instance == null) {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        } else {
            Destroy(gameObject);
        }

        rb = GetComponent<Rigidbody2D>();
        anim = transform.Find("Animation").GetComponent<Animator>();
        state = State.Walking;
    }
    #endregion`

2021-10-04 15:00 UTC, SlightlyDarkerBlackOne commented on Assets/Scripts/Controls/Leash.cs
> +                //move the end of leash from where it was left off to the new position
Instead of commenting this could have been a method SetLeashToPlayerHuman() with additional comments on the method if needed.

2021-10-04 15:03 UTC, SlightlyDarkerBlackOne commented on Assets/Scripts/Controls/Leash.cs
> +
Much clearer to understand if variables are named correctly.
originalDistance could also be defaultLeashDistance or minLeashDistance

`private bool DogInRange()
    {
        var currentDistance = Vector2.Distance(playerHuman.transform.position, playerDog.transform.position);
        if (currentDistance > originalDistance) 
            return false;
        return true;
    }`

2021-10-04 22:46 UTC, SlightlyDarkerBlackOne commented on Assets/Scripts/Controls/PlayerController2D.cs
> +        if (!leash.activeSelf)
Putting an if over all these methods is the lazy way of doing it. The problem is Move() method has switch case functionality which checks what state player is in. (Is it moving or not)
Due to this, if statement bug occurs if you hold any movement key and switch leash on and off, the uncontrolled player starts moving indefinitely on it's own.

2021-10-04 22:52 UTC, SlightlyDarkerBlackOne requested changes
Molim te da promijenis ove parametre prije nego sto merge-amo.

2021-10-05 13:22 UTC, SlightlyDarkerBlackOne approved these changes
Okej super, bar nije zbuggano vise tak. Svejedno moramo pogledat za dinamicnu uzicu jer sad mozes playera teleportirat van mape.

2021-10-05 13:22 UTC, merged

2021-10-05 13:34 UTC, Sarvihaara commented
Da, to s teleportacijom je samo privremeni fix jer me malo zbunjuje kako vratiti uzicu bez da se produlji ostatak nje, to cu jos vidjeti